format = """
[](fg:#556FFF)\
$os\
$username\
[](bg:#1D1F28 fg:#556FFF)\
$directory\
[](fg:#1D1F28 bg:#556FFF)\
$git_branch\
$git_status\
[](fg:#556FFF bg:#3FDCEE)\
$docker_context\
[](fg:#3FDCEE bg:#4D6D8E)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4D6D8E bg:#1D1F28)\
$time\
[ ](fg:#1D1F28)\
"""

[username]
show_always = true
style_user = "bg:#556FFF"
style_root = "bg:#556FFF"
format = '[🎉 $user ]($style)'

[os]
style = "bg:#C574DD"
disabled = true

[directory]
style = "bg:#1D1F28"
format = "[ $path ]($style)"
truncation_length = 1

[c]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#3FDCEE"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#556FFF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#556FFF"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:#4D6D8E"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1D1F28"
format = '[ ⏱  $time ]($style)'
